export const ListaDeIdiomas = {
  VistaMenu: {
    es: {
      Perfil: "Perfil",
      Paqueteria: "Paquetería",
      Pedidos: "Pedidos",
      Agencias: "Agencias",
      Productos: "Productos",
      Usuarios: "Usuarios",
      Operaciones: "Operaciones",
      Movimientos: "Movimientos",
      Ocurres: "Ocurres",
      Configuracion: "Configuración",
      Cargas: "Cargas",
      Envios: "Envios",
      Ubicaciones: "Ubicaciones",
      Apariencia: "Apariencia",
    },
    en: {
      Perfil: "Profile",
      Paqueteria: "Shipping",
      Pedidos: "Orders",
      Agencias: "Agencies",
      Productos: "Products",
      Usuarios: "Users",
      Operaciones: "Operations",
      Movimientos: "Movements",
      Ocurres: "Ocurres",
      Configuracion: "Configuration",
      Cargas: "Loads",
      Envios: "Deliveries",
      Ubicaciones: "Locations",
      Apariencia: "Appearance",
    },
  },
  VistaPerfil: {
    es: {
      Perfil: "Perfil",
      Correo: "Correo",
      Telefono: "Teléfono",
      FechaDeCreacion: "Fecha de creación",
    },
    en: {
      Perfil: "Profile",
      Correo: "Email",
      Telefono: "Phone",
      FechaDeCreacion: "Creation date",
    },
  },
  VistaAgencias: {
    es: {
      Agencias: "Agencias",
      RegistrarAgencia: "Registrar Agencia",
      AdministrarAgencias: "Administrar Agencias",
    },
    en: {
      Agencias: "Agencies",
      RegistrarAgencia: "Register Agency",
      AdministrarAgencias: "Manage Agencies",
    },
  },
  VistaRegistrarAgencia: {
    es: {
      RegistrarAgencia: "Registrar Agencia",
      NombreDeLaAgencia: "Nombre de la agencia",
      NombreLegalDeLaAgencia: "Nombre legal de la agencia (DBA)",
      TelAgencia: "Tel. Agencia",
      Fax: "Fax",
      CorreoAgencia: "Correo Agencia",
      CorreoAgencia2: "Correo Agencia #2 (Opcional)",
      NombreRepresentanteVentas: "Nombre representante ventas",
      TelRepresentante: "Tel. Representante",
      NombreDelDueño: "Nombre del dueño",
      TelDueño: "Tel. Dueño",
      NombreDelManager: "Nombre del manager",
      TelManager: "Tel. Manager",
      NoLicencia: "No. Licencia",
      NoSalesTax: "No. Sales Tax",
      SS: "S.S",
      CopiaID: "Copia ID",
      CopiaLicencia: "Copia Licencia",
      CopiaSalesTax: "Copia Sales Tax",
    },
    en: {
      RegistrarAgencia: "Register Agency",
      NombreDeLaAgencia: "Agency name",
      NombreLegalDeLaAgencia: "Legal name of the agency (DBA)",
      TelAgencia: "Tel. Agency",
      Fax: "Fax",
      CorreoAgencia: "Email Agency",
      CorreoAgencia2: "Email Agency #2 (Optional)",
      NombreRepresentanteVentas: "Name of sales representative",
      TelRepresentante: "Tel. Representative",
      NombreDelDueño: "Name of owner",
      TelDueño: "Tel. Owner",
      NombreDelManager: "Name of manager",
      TelManager: "Tel. Manager",
      NoLicencia: "No. License",
      NoSalesTax: "No. Sales Tax",
      SS: "S.S",
      CopiaID: "Copy ID",
      CopiaLicencia: "Copy License",
      CopiaSalesTax: "Copy Sales Tax",
    },
  },
  VistaAdministrarAgencias: {
    es: {
      AdministrarAgencias: "Administrar Agencias",
      BuscarAgencia: "Buscar Agencia (Nombre, País, Estado, Ciudad, CP)",
      EstatusDeLasAgencia: "Estatus de las agencias:",
      Activa: "Activa",
      Desactivada: "Desactivada",
      Operaciones: "Operaciones:",
      RegistrarAgencia: "Registrar Agencia",
    },
    en: {
      AdministrarAgencias: "Manage Agencies",
      BuscarAgencia: "Search Agency (Name, Country, State, City, Zip Code)",
      EstatusDeLasAgencia: "Agencies status:",
      Activa: "Active",
      Desactivada: "Disabled",
      Operaciones: "Operations:",
      RegistrarAgencia: "Register Agency",
    },
  },
  VistaEditarAgencia: {
    es: {
      EditarAgencia: "Editar Agencia",
      NombreDeLaAgencia: "Nombre de la agencia",
      NombreLegalDeLaAgencia: "Nombre legal de la agencia (DBA)",
      TelAgencia: "Tel. Agencia",
      Fax: "Fax",
      CorreoAgencia: "Correo Agencia",
      CorreoAgencia2: "Correo Agencia #2 (Opcional)",
      NombreRepresentanteVentas: "Nombre representante ventas",
      TelRepresentante: "Tel. Representante",
      NombreDelDueño: "Nombre del dueño",
      TelDueño: "Tel. Dueño",
      NombreDelManager: "Nombre del manager",
      TelManager: "Tel. Manager",
      NoLicencia: "No. Licencia",
      NoSalesTax: "No. Sales Tax",
      SS: "S.S",
      CopiaID: "Copia ID",
      CopiaLicencia: "Copia Licencia",
      CopiaSalesTax: "Copia Sales Tax",
    },
    en: {
      EditarAgencia: "Edit Agency",
      NombreDeLaAgencia: "Agency name",
      NombreLegalDeLaAgencia: "Legal name of the agency (DBA)",
      TelAgencia: "Tel. Agency",
      Fax: "Fax",
      CorreoAgencia: "Email Agency",
      CorreoAgencia2: "Email Agency #2 (Optional)",
      NombreRepresentanteVentas: "Name of sales representative",
      TelRepresentante: "Tel. Representative",
      NombreDelDueño: "Name of owner",
      TelDueño: "Tel. Owner",
      NombreDelManager: "Name of manager",
      TelManager: "Tel. Manager",
      NoLicencia: "No. License",
      NoSalesTax: "No. Sales Tax",
      SS: "S.S",
      CopiaID: "Copy ID",
      CopiaLicencia: "Copy License",
      CopiaSalesTax: "Copy Sales Tax",
    },
  },
  VistaAdministrarProductosDeLaAgencia: {
    es: {
      AgenciaSeleccionada: "Agencia seleccionada:",
      ProductosAsignados: "Productos asignados",
      AsignarNuevoProducto: "Asignar nuevo producto",
      BuscarProducto: "Buscar producto",
      RegistrarProducto: "Registrar producto",
    },
    en: {
      AgenciaSeleccionada: "Selected agency:",
      ProductosAsignados: "Assigned products",
      AsignarNuevoProducto: "Assign new product",
      BuscarProducto: "Search product",
      RegistrarProducto: "Register product",
    },
  },
  ModalInformacionDelProducto: {
    es: {
      DetallesDelProducto: "Detalles del producto",
      Producto: "Producto",
      PrecioPublico: "Precio público",
      Comision: "Comisión",
      LibraExtra: "Libra extra",
      PesoSinCobro: "Peso sin cobro",
      PesoMaximo: "Peso máximo",
      Medidas: "Medidas",
      Ancho: "Ancho",
      Alto: "Alto",
      Largo: "Largo",
    },
    en: {
      DetallesDelProducto: "Product details",
      Producto: "Product",
      PrecioPublico: "Public price",
      Comision: "Commission",
      LibraExtra: "Extra weight",
      PesoSinCobro: "Weight without charge",
      PesoMaximo: "Maximum weight",
      Medidas: "Dimensions",
      Ancho: "Width",
      Alto: "Height",
      Largo: "Length",
    },
  },
  ModalSubirArchivoSeleccionar: {
    es: {
      Remitentes: "Remitentes",
      Destinatarios: "Destinatarios",
      SeleccionarArchivos: "Seleccionar archivo",
      MensajeParteUno: "Para subir la información de los",
      MensajeParteDos: "a la agencia",
      MensajeParteTres: "debes seleccionar un archivo en formato XLSX.",
    },
    en: {
      Remitentes: "Senders",
      Destinatarios: "Recipients",
      SeleccionarArchivos: "Select file",
      MensajeParteUno: "To upload the information of the",
      MensajeParteDos: "to the agency",
      MensajeParteTres: "you must select a file in XLSX format.",
    },
  },
  ModalSubirArchivoError: {
    es: {
      Remitentes: "Remitentes",
      Destinatarios: "Destinatarios",
      MensajeParteUno:
        "¡Oops! Parece que algo salió mal al insertar la información de los",
      MensajeParteDos: "por favor, intenta de nuevo más tarde.",
    },
    en: {
      Remitentes: "Senders",
      Destinatarios: "Recipients",
      MensajeParteUno:
        "¡Oops! Looks like something went wrong while inserting the information of the",
      MensajeParteDos: "please try again later.",
    },
  },
  ModalSubirArchivoCompletado: {
    es: {
      Remitentes: "Remitentes",
      Destinatarios: "Destinatarios",
      MensajeParteUno: "La información de los",
      MensajeParteDos:
        "ha sido insertada con éxito en la base de datos y asignada a la agencia.",
    },
    en: {
      Remitentes: "Senders",
      Destinatarios: "Recipients",
      MensajeParteUno: "The information of the",
      MensajeParteDos:
        "has been inserted successfully in the database and assigned to the agency.",
    },
  },
  ModalSubirArchivoSubiendo: {
    es: {
      Subiendo: "Subiendo... ",
      NoCierresEstaVentana: "¡No cierres esta ventana!",
    },
    en: {
      Subiendo: "Uploading... ",
      NoCierresEstaVentana: "Don't close this window!",
    },
  },
  GoogleAPI: {
    es: {
      BuscarDireccion: "Buscar dirección",
      DetallesDeLaDireccion: "Detalles de la dirección",
      Pais: "País",
      CodigoPais: "Código de país",
      Estado: "Estado",
      CodigoEstado: "Código de estado",
      Ciudad: "Ciudad",
      CodigoPostal: "Código postal",
      Direccion: "Dirección",
    },
    en: {
      BuscarDireccion: "Search address",
      DetallesDeLaDireccion: "Address details",
      Pais: "Country",
      CodigoPais: "Country code",
      Estado: "State",
      CodigoEstado: "State code",
      Ciudad: "City",
      CodigoPostal: "Postal code",
      Direccion: "Address",
    },
  },
  Botones: {
    es: {
      Guardar: "Guardar",
      Cancelar: "Cancelar",
      Regresar: "Regresar",
      Actualizar: "Actualizar",
      Ver: "Ver",
      Subir: "Subir",
      Seleccionar: "Seleccionar",
      Asignar: "Asignar",
      CerrarSesion: "Cerrar sesión",
      DescargarExcel: "Descargar Excel",
      Activar: "Activar",
      Desactivar: "Desactivar",
    },
    en: {
      Guardar: "Save",
      Cancelar: "Cancel",
      Regresar: "Back",
      Actualizar: "Update",
      Ver: "See",
      Subir: "Upload",
      Seleccionar: "Select",
      Asignar: "Assign",
      CerrarSesion: "Log out",
      DescargarExcel: "Download Excel",
      Activar: "Activate",
      Desactivar: "Deactivate",
    },
  },
  MensajesDeError: {
    es: {
      Requerido: "¡Este campo es obligatorio! ⚠️",
      Archivo: "¡Por favor, selecciona un archivo! ⚠️",
      Max10: "¡Este campo no puede tener más de 10 caracteres! 🔠",
      Max100: "¡Este campo no puede tener más de 100 caracteres! 🔠",
      Min10: "¡Este campo no puede tener menos de 10 caracteres! 🔠",
    },
    en: {
      Requerido: "¡This field is required! ⚠️",
      Archivo: "¡Please select a file! ⚠️",
      Max10: "¡This field cannot have more than 10 characters! 🔠",
      Max100: "¡This field cannot have more than 100 characters! 🔠",
      Min10: "¡This field cannot have less than 10 characters! 🔠",
    },
  },
  Placeholder: {
    es: "Escriba aquí...",
    en: "Write here...",
  },
  Resultados: {
    es: {
      NoResultados: "¡Oops! No se encontraron resultados.",
      Obtuvimos: "Obtuvimos",
      Resultados: "resultados",
    },
    en: {
      NoResultados: "Oops! No results were found.",
      Obtuvimos: "We got",
      Resultados: "results",
    },
  },
  Paginacion: {
    es: {
      Pagina: "Página",
      De: "de",
    },
    en: {
      Pagina: "Page",
      De: "of",
    },
  },
};
